# Generated by Django 5.2.5 on 2025-08-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
